# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/base/logo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setProperty("current_album_path", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.album = QtWidgets.QVBoxLayout()
        self.album.setObjectName("album")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cb_artist = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_artist.sizePolicy().hasHeightForWidth())
        self.cb_artist.setSizePolicy(sizePolicy)
        self.cb_artist.setEditable(True)
        self.cb_artist.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cb_artist.setObjectName("cb_artist")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_artist)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cb_album = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_album.sizePolicy().hasHeightForWidth())
        self.cb_album.setSizePolicy(sizePolicy)
        self.cb_album.setEditable(True)
        self.cb_album.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cb_album.setObjectName("cb_album")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_album)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cb_genre = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_genre.sizePolicy().hasHeightForWidth())
        self.cb_genre.setSizePolicy(sizePolicy)
        self.cb_genre.setEditable(True)
        self.cb_genre.setObjectName("cb_genre")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_genre)
        self.album.addLayout(self.formLayout)
        self.tb_tracks = QtWidgets.QTableView(self.centralwidget)
        self.tb_tracks.setObjectName("tb_tracks")
        self.album.addWidget(self.tb_tracks)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout_2.addWidget(self.btn_export)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.album.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.album)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music Manager"))
        self.label.setText(_translate("MainWindow", "Artist"))
        self.label_2.setText(_translate("MainWindow", "Album"))
        self.label_3.setText(_translate("MainWindow", "Genre"))
        self.btn_export.setText(_translate("MainWindow", "Export"))
        self.pushButton.setText(_translate("MainWindow", "test1"))
import icons_rc
